// <auto-generated />
namespace Repositorio.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_cliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_cliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201602162234466_Add_cliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
