// <auto-generated />
namespace Repositorio.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_email));
        
        string IMigrationMetadata.Id
        {
            get { return "201602250021322_add_email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
